---
#  - name: Remove old filebeat
#    become: yes
#    shell: apt-get remove --purge filebeat --yes && rm -Rf /usr/share/filebeat/module/postfix && rm -Rf /etc/filebeat

  - name: Install Filebeat
    become: yes
    shell: cd /tmp && curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.11.2-amd64.deb && dpkg -i filebeat-7.11.2-amd64.deb

  - name: Add filebeat.yml config into dir
    become: yes
    template:
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
      mode: 0600
    tags:
      - reload
  
  - name: Disable module nginx before cp file
    become: yes
    shell: filebeat modules disable nginx
    tags:
      - reload

  - name: Add modules into filebeat modules.d
    become: yes
    copy: src={{ item }} dest=/etc/filebeat/modules.d/ owner=root mode=644
    with_fileglob:
      - ./modules.d/*
    tags:
      - reload

  - name: Enable module nginx
    become: yes
    shell: filebeat modules enable nginx
    tags:
      - reload
  
  - name: Setup filebeat - this will take a while...
    become: yes
    shell: filebeat setup
    ignore_errors: true

  - name: Start service
    become: yes
    service: name=filebeat state=restarted
    tags:
      - reload
