---
  - name: Install Filebeat
    become: yes
    shell: cd /tmp && curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.12.0-amd64.deb && dpkg -i filebeat-7.12.0-amd64.deb

  - name: Add filebeat.yml config into dir
    become: yes
    template: src=filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml
      mode: 0600
  
  - name: Add postfix modules into filebeat
    become: yes
    synchronize: 
      src: postfix
      dest: /usr/share/filebeat/module/postfix

  - name: Add modules into filebeat modules.d
    become: yes
    copy: src={{ item }} dest=/etc/filebeat/modules.d/ owner=root mode=644
    with_fileglob:
      - ./modules.d/*
  
  - name: Enable module nginx
    become: yes
    shell: filebeat modules enable nginx

  - name: Enable module postfix
    become: yes
    shell: filebeat modules enable postfix
  
  - name: Setup filebeat - this will take a while...
    become: yes
    shell: filebeat setup

  - name: Start service
    service: name=filebeat state=restarted