---
  - name: Start watchtower, manually pull(interval 120s)
    docker:
      name: watchtower
      image: centurylink/watchtower
      command: --cleanup --no-pull --interval 120
      pull: missing
      state: started
      restart_policy: always
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tags:
      - start

  - name: Stop and remove container
    docker:
      name: watchtower
      image: centurylink/watchtower
      state: absent
    tags:
      - stop
      - update-all-container

  - name: Start,pull,update container immediately(interval 300s)
    docker:
      name: watchtower
      image: centurylink/watchtower
      command: --cleanup --interval 300
      pull: missing
      state: started
      restart_policy: on-failure
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tags:
      - update-all-container
