---
  - name: Start watchtower
    docker:
      name: watchtower
      image: centurylink/watchtower
      command: --cleanup --no-pull --interval 180
      pull: missing
      state: started
      restart_policy: always
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tags:
      - start

  - name: Stop and remove container
    docker:
      name: watchtower
      image: centurylink/watchtower
      state: absent
    tags:
      - stop
      - update-all-container

  - name: Start and update all container
    docker:
      name: watchtower
      image: centurylink/watchtower
      command: --cleanup --interval 300
      pull: missing
      state: started
      restart_policy: no
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tags:
      - update-all-container
