---
# file: docker.yml
- hosts: '{{ target }}'
  sudo: yes
  vars_files:
    - '/etc/ansible/target/{{ inventory_hostname }}/hostname'
    - '/etc/ansible/target/{{ inventory_hostname }}/{{ domain }}'
  roles:
    - docker
    - nginx

- hosts: localhost
  connection: local
  sudo: yes
  vars_files:
    - '/etc/ansible/target/{{ target }}/hostname'
  roles:
    - dns
  tasks:
    # create mail account
    - name: Add mail account into vmail file
      shell: bash -c "jq '.mailaddr += [\"{{ domain }}@{{ hostname }}\"]' /etc/ansible/target/{{ target }}/vmail > /tmp/vmail_{{ target }}" && bash -c "cp /tmp/vmail_{{ target }} /etc/ansible/target/{{ target }}/vmail"
      tags:
        - start
