---
# file: docker.yml
- hosts: '{{ target }}'
  sudo: yes
  vars_files:
    - '/etc/ansible/target/{{ inventory_hostname }}/hostname'
    - '/etc/ansible/target/{{ inventory_hostname }}/{{ domain }}'
  roles:
    - docker
    - nginx

- hosts: localhost
  connection: local
  sudo: yes
  vars_files:
    - '/etc/ansible/target/{{ target }}/hostname'
  roles:
    - dns
  tasks:
    # create mail account
    - name: Check if mail account already exists
      shell: bash -c "cat /etc/ansible/target/{{ target }}/vmail | grep {{ domain }} | wc -l"
      register: has_account
      tags:
        - start
    - name: Add mail account into vmail file when not exists
      shell: bash -c "jq '.mailaddr += [\"{{ domain }}@{{ hostname }}\"]' /etc/ansible/target/{{ target }}/vmail > /tmp/vmail_{{ target }}" && bash -c "cp /tmp/vmail_{{ target }} /etc/ansible/target/{{ target }}/vmail"
      when: "'{{ has_account.stdout }}' == '0'"
      tags:
        - start
