---
# Initial linode image and create remote user account for ansible.
- hosts: "{{ target }}"
  roles:
    - init

- hosts: localhost
  connection: local
  sudo: yes
  tasks:
    - name: Upgrade debian package
      apt: update_cache=yes cache_valid_time=3600
    - shell: bash -c "apt-get upgrade --assume-yes &> /var/log/system_upgrade.log"
      ignore_errors: yes

