---
# Mail Server from docker container
- hosts: "{{ target }}"
  become: yes
  vars_files:
    - '/etc/ansible/target/{{ inventory_hostname }}/hostname'
    - '/etc/ansible/target/{{ inventory_hostname }}/vmail'
  roles:
    - mail
