- hosts: "{{ target }}"
  vars_files:
    - '/etc/ansible/target/all/security'
  become: yes
  roles:
  - fail2ban
  - firewall
  tasks:
  - name: Disallow root login by sshd
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"

  - name: Allow specify group login in ssh
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^## Group', line: '## Group' }
      - { regexp: '^AllowGroups', line: 'AllowGroups userssh usersftp answerable' }

  - name: Deny specify group login in ssh
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    when: ssh_master_ip is defined
    with_items:
      - { regexp: '^## Deny by ip', line: '## Deny by ip' }
      - { regexp: '^Match Address \*', line: 'Match Address *,{{ ssh_master_ip }} User answerable' }
      - { regexp: '^  DenyUsers answerable', line: '  DenyUsers answerable' }

  - name: Disallow answerable login by password
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^## Answerable specify config', line: '## Answerable specify config' }
      - { regexp: '^Match User answerable', line: 'Match User answerable' }
      - { regexp: '^  PasswordAuthentication', line: '  PasswordAuthentication no' }

  - name: Force sftp group login only by sftp
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^## SFTP', line: '## SFTP' }
      - { regexp: '^Match Group usersftp', line: 'Match Group usersftp' }
      - { regexp: '^  ChrootDirectory %h', line: '  ChrootDirectory %h' }
      - { regexp: '^  ForceCommand internal-sftp', line: '  ForceCommand internal-sftp' }
      - { regexp: '^  AllowTcpForwarding no', line: '  AllowTcpForwarding no' }
      - { regexp: '^  X11Forwarding no', line: '  X11Forwarding no' }

  - name: Force answerable login only with pubkey
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^  AuthenticationMethods publickey"
      insertafter: '^Match User answerable'
      line: '  AuthenticationMethods publickey'

  - name: Reload SSHD
    service: name=sshd state=reloaded



