---
  - name: Stop and remove container
    docker:
      name: dovecot
      image: netivism/docker-postfix-dovecot
      state: absent
    tags:
      - stop
      - restart

  - name: Check if python-pip is installed
    command: dpkg-query -l python-pip
    register: pip_is_installed
    failed_when: pip_is_installed.rc > 1
    changed_when: no
    tags:
      - start

  - name: Remove python-pip only if installed
    apt: name=python-pip state=absent
    when: pip_is_installed.rc == 0
    tags:
      - start

  - name: Install Python Pip
  # use easy_install because of python bug http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread
    easy_install:
      name: pip
    tags:
      - start

  - name: Install Docker-py
    pip:
      name: docker-py
      version: 1.2.1
      state: present
    tags:
      - start

  - name: Make sure docker is running
    service:
      name: docker
      state: started
    tags:
      - start

  - name: Create /var/vmail if not exists
    file:
      path: /var/vmail
      state: directory
      mode: 0755
    tags:
      - start

  - name: Make sure smtp not start
    service: name=exim4 state=stopped
    ignore_errors: yes
    tags:
      - start

  - name: Start container
    docker:
      name: dovecot
      image: netivism/docker-postfix-dovecot
      pull: always
      restart_policy: always
      expose:
       - 993
       - 587
       - 25
       - 465
      ports:
      - "993:993"
      - "587:587"
      - "25:25"
      - "465:465"
      env:
        MAILNAME: "{{ mailname }}"
        MAILADDR: "{{ mailaddr }}"
        TZ: "Asia/Taipei"
      volumes:
      - /etc/postfix
      - /etc/ssl
      - /etc/dovecot
      - /var/vmail:/home/vmail
      - /var/vmail/log:/var/log
      - /var/vmail/opendkim:/etc/opendkim
    tags:
      - start
      - restart

  - name: Wait for service startup
    wait_for: port=587 delay=10
    tags:
      - start
      - restart

  - name: Save mail account and password into vmail_account
    fetch: src=/var/vmail/vmail_account dest=/etc/ansible/target/{{ inventory_hostname }}/vmail_account flat=yes
    tags:
      - start
      - restart
  - name: Save DKIM key into vmail_dkim
    fetch: src=/var/vmail/vmail_dkim dest=/etc/ansible/target/{{ inventory_hostname }}/vmail_dkim flat=yes
    tags:
      - start
      - restart

  - name: Create site's smtp configuration file
    stat: path=/var/www/sites/{{ domain }}/sites/default/smtp.settings.php
    register: smtpsettings
    tags:
      - site-setting

  - template: src=smtp.settings.php.j2 dest=/var/www/sites/{{ domain }}/sites/default/smtp.settings.php
    when: smtpsettings.stat.exists == False
    tags:
      - site-setting

  - stat: path=/var/www/sites/{{ domain }}/sites/default/settings.php
    register: settings
    tags:
      - site-setting

  - name: Include smtp conf into drupal settings file
    lineinfile:
      dest="/var/www/sites/{{ domain }}/sites/default/settings.php"
      regexp=""
      line="if(is_file(dirname(__FILE__).'/smtp.settings.php')){ @include_once('smtp.settings.php'); }"
      insertafter=EOF
    when: settings.stat.exists == True
    tags:
      - site-setting

  - name: Setup site wide mail info
    shell: cd /var/www/sites/{{ domain }} && drush neticrm-set-domain
    ignore_errors: yes
    tags:
      - site-setting

  - name: Send welcome mail
    shell: cd /var/www/sites/{{ domain }} && drush neticrm-welcome-mail
    ignore_errors: yes
    tags:
      - welcome
