---
  - name: remove old google-cloud-sdk because conflict python-openssl
    apt: name=google-cloud-sdk state=absent
    become: yes
    ignore_errors: true

  - name: remove old apt list
    file: path=/etc/apt/sources.list.d/packages_cloud_google_com_apt.list state=absent
    ignore_errors: true

  - name: install google-cloud-sdk container
    become: yes
    shell: docker pull netivism/docker-google-cloud-sdk

  - name: Create gcloud directory
    file: path=/backup/gcloud state=directory mode=0755
    become: yes

  - name: Copy gcloud auth configuration file to remote
    copy: src=gcauth.json dest=/backup/gcloud/gcauth.json
    become: yes

  - name: Activite gcloud
    shell: docker run -v /backup/gcloud:/backup/gcloud --name gcloud-config netivism/docker-google-cloud-sdk gcloud auth activate-service-account --key-file /backup/gcloud/gcauth.json
    ignore_errors: true
    become: yes

