---
  - name: Split domain to group variables.
    set_fact:
      sub: "{{ domain | split('.') }}"
    tags:
      - create
      - start
      - alias
      - offline
      - suspend 
      - remove

  - name: Check if master domain not exist.
    shell: linode domain show {{ main_domain }} | grep find
    register: domain_check
    ignore_errors: true
    tags:
      - create

  - name: Create a master domain.
    shell: linode domain create {{ main_domain }} mis@netivism.com.tw
    when: domain_check.stderr != ""
    tags:
      - create

  - name:  Check if domain record not exist.
    shell: bash -c "linode domain record-list {{ main_domain }} | grep {{ sub.0 }} | wc -l"
    register: domain_record_check
    ignore_errors: true
    tags:
      - start
      - offline
      - suspend
      - remove
      - alias

  - name: Create domain record.
    shell: linode domain record-create -l {{ main_domain }} -t CNAME -n {{ domain }} -R {{ hostname }}
    when: domain_record_check|bool == false and '{{ main_domain }}' in '{{ domain }}'
    ignore_errors: true
    tags:
      - start
      - alias

  - name: Make domain offline.
    shell: linode domain record-update -l {{ main_domain }} -t CNAME -m {{ sub.0 }} -R offline.neticrm.tw
    when: domain_record_check != "0" and '{{ main_domain }}' in '{{ domain }}'
    ignore_errors: true
    tags:
      - offline
      - suspend

  - name: Remove domain record.
    shell: linode domain record-delete -l {{ main_domain }} -t CNAME -m {{ sub.0 }}
    when: domain_record_check != "0" and '{{ main_domain }}' in '{{ domain }}'
    ignore_errors: true
    tags:
      - remove
