---
  - name: Copy drush execute file
    copy: src=drush dest=/usr/local/bin/drush mode=0755 owner=root

  - name: Fetch sites-unavailable repo from github
    git: repo=https://github.com/NETivism/sites-unavailable.git dest=/var/www/sites-unavailable update=yes clone=yes accept_hostkey=true

  - name: fstrim file
    copy: src=fstrim.sh dest=/usr/local/bin/fstrim.sh mode=0755 owner=root

  - name: Syslive file
    copy: src=syslive.sh dest=/usr/local/bin/syslive.sh mode=0755 owner=root

  - name: Mysql Param check file
    copy: src=check_mysql_param.sh dest=/usr/local/bin/check_mysql_param.sh mode=0755 owner=root

  - name: Module check file
    copy: src=check_module.sh dest=/usr/local/bin/check_module.sh mode=0755 owner=root

  - name: Module schema version check file
    copy: src=check_module_version.sh dest=/usr/local/bin/check_module_version.sh mode=0755 owner=root

  - name: Update script files
    copy: src=../../neticrm/files/drupal_cron.sh dest=/usr/local/bin/drupal_cron.sh mode=0755 owner=answerable
  - copy: src=../../neticrm/files/drupal_cache_clear.sh dest=/usr/local/bin/drupal_cache_clear.sh mode=0755 owner=answerable
  - copy: src=../../neticrm/files/neticrm_update.sh dest=/usr/local/bin/neticrm_update.sh mode=0755 owner=answerable
