- hosts: "{{ target }}"                                                            
  sudo: yes                                                                        
  roles:
    - ../roles/common
  tasks:                                                                           
  - name: check neticrm schema version
    shell: check_module_version.sh neticrm_update onlycrm
    register: output
  - debug: var=output.stdout_lines 
