- hosts: "{{ target }}"                                                            
  become: yes                                                                        
  tasks:                                                                           
  - name: check neticrm schema version
    shell: check_module_version.sh neticrm_update onlycrm
    register: output
  - debug: var=output.stdout_lines 
  #  - name: check neticrm schema version
  #  shell: check_module_version.sh civicrm_dmenu onlycrm
  #  register: output
  #- debug: var=output.stdout_lines 
