---
# Initial linode image and create remote user account for ansible.
- hosts: "{{ target }}"
  remote_user: root
  sudo: no
  roles:
    - init

- hosts: localhost
  connection: local
  sudo: yes
  tasks:
    - name: Generate correct locale
      command: sed -i -e 's/# zh_TW.UTF-8 UTF-8/zh_TW.UTF-8 UTF-8/' /etc/locale.gen
    - command: dpkg-reconfigure --frontend=noninteractive locales
    - command: update-locale LANG=zh_TW.UTF-8

    - name: Create target directory.
      file: path=/etc/ansible/target/{{ inventory_hostname }} state=directory

    - name: Create hostname directory.
      template: src=roles/init/templates/hostname.j2 dest=/etc/ansible/target/{{ inventory_hostname }}/hostname
    - name: Create redirect file.
      template: src=roles/init/templates/redirect.j2 dest=/etc/ansible/target/{{ inventory_hostname }}/redirect
    - name: Create user file.
      template: src=roles/init/templates/user.j2 dest=/etc/ansible/target/{{ inventory_hostname }}/user
    - name: Create vmail file.
      template: src=roles/init/templates/vmail.j2 dest=/etc/ansible/target/{{ inventory_hostname }}/vmail

    - name: Upgrade debian package
      apt: update_cache=yes cache_valid_time=3600
    - shell: bash -c "apt-get upgrade --assume-yes &> /var/log/system_upgrade.log"

    - name: Copy hostname to remote
      shell: echo "{{ hostname }}" > /etc/ansible/fqdn
