---
- name: Cron - copy to specify location
  copy: src=drupal_cron.sh dest=/usr/local/bin/drupal_cron.sh mode=0755 owner=answerable
  become: yes
  become_method: sudo
  tags:
    - load
    - deploy-7
    - deploy-6

- name: Cron - setup cronjob
  copy: src=drupal_cron dest=/etc/cron.d/drupal_cron mode=0644 owner=root
  become: yes
  become_method: sudo
  tags:
    - load
    - deploy-7
    - deploy-6

- name: deploy private key for fetching git repository
  copy: src=id_rsa dest=/home/answerable/.ssh/id_rsa mode=0400 owner=answerable
  tags:
    - load
    - deploy-7
    - deploy-6

- name: Create directory
  file: path={{ item }} state=directory mode=0755 owner=answerable
  become: yes
  become_method: sudo
  with_items:
    - /mnt/neticrm-7
    - /mnt/neticrm-6
  tags:
    - load
    - deploy-7
    - deploy-6

# neticrm 7
- name: Global settings
  copy: src=global_7.inc dest=/mnt/neticrm-7/global.inc mode=0755 owner=answerable
  tags:
    - load
    - deploy-7

- name: Deploy neticrm-7
  git: repo=https://github.com/NETivism/neticrm.git version=master dest=/mnt/neticrm-7/civicrm update=no clone=yes accept_hostkey=true
  tags: deploy-7
- shell: cd /mnt/neticrm-7/civicrm/neticrm && git checkout 7.x-master && git pull
  tags: deploy-7
- shell: cd /mnt/neticrm-7/civicrm/drupal && git checkout 7.x-master && git pull
  tags: deploy-7
- git: repo=git@git.netivism.com.tw:netivism/neticrmp.git version=7.x-master dest=/mnt/neticrm-7/neticrmp update=no clone=yes accept_hostkey=true
  tags: deploy-7

# neticrm 6
- name: Global settings
  copy: src=global_6.inc dest=/mnt/neticrm-6/global.inc mode=0755 owner=answerable
  tags:
    - load
    - deploy-6

- name: Deploy neticrm-6
  git: repo=https://github.com/NETivism/neticrm.git version=master dest=/mnt/neticrm-6/civicrm update=no clone=yes accept_hostkey=true
  tags:
    - deploy-6
- shell: cd /mnt/neticrm-6/civicrm/neticrm && git checkout 6.x-master && cd /mnt/neticrm-6/civicrm/drupal && git checkout 6.x-master
  tags:
    - deploy-6
- git: repo=git@git.netivism.com.tw:netivism/neticrmp.git version=6.x-master dest=/mnt/neticrm-6/neticrmp update=no clone=yes accept_hostkey=true
  tags:
    - deploy-6


# upgrade neticrm 7
- name: upgrade netiCRM 7
  shell: cd /mnt/neticrm-7/civicrm && git checkout master && git fetch && git reset --hard origin/master
  tags:
    - upgrade-7
    - upgrade-7-civicrm
- shell: cd /mnt/neticrm-7/civicrm/neticrm && git checkout 7.x-master && git pull
  tags:
    - upgrade-7
    - upgrade-7-neticrm
- shell: cd /mnt/neticrm-7/civicrm/drupal && git checkout 7.x-master && git pull
  tags:
    - upgrade-7
    - upgrade-7-drupal
- git: repo=git@git.netivism.com.tw:netivism/neticrmp.git version=7.x-master dest=/mnt/neticrm-7/neticrmp update=yes clone=no accept_hostkey=true
  tags:
    - upgrade-7
    - upgrade-7-neticrmp

# upgrade neticrm 6
- name: upgrade netiCRM 6
  shell: cd /mnt/neticrm-6/civicrm && git checkout master && git fetch && git reset --hard origin/master
  tags:
    - upgrade-6
    - upgrade-6-civicrm
- shell: cd /mnt/neticrm-6/civicrm/neticrm && git checkout 6.x-master && git pull && cd /mnt/neticrm-6/civicrm/drupal && git checkout 6.x-master && git pull
  tags:
    - upgrade-6
    - upgrade-6-neticrm
- shell: cd /mnt/neticrm-6/neticrmp && git fetch --all && git reset --hard origin/6.x-master
  tags:
    - upgrade-6
    - upgrade-6-neticrmp

# Reload and update global config for each site
- name: List settings for all sites
  shell: ls -1 /var/www/sites/*/sites/*/settings.php
  register: settings
  tags:
    - all-sites

- name: List setting in specific domain
  shell: ls -1 /var/www/sites/{{ domain }}/sites/*/settings.php
  register: settings
  tags:
    - single-site

- name: include global
  lineinfile:
    dest: "{{ item }}"
    regexp: "^defined\\('VERSION"
    line: "defined('VERSION') ? @include_once('/mnt/neticrm-'.substr(VERSION, 0, strpos(VERSION, '.')).'/global.inc') : @include_once('/mnt/neticrm-6/global.inc');"
  with_items: settings.stdout_lines
  become: yes
  become_method: sudo
  tags:
    - all-sites
    - single-site

- name: include local
  lineinfile:
    dest: "{{ item }}"
    insertafter: "^defined\\('VERSION"
    line: "if(is_file(dirname(__FILE__).'/local.settings.php')){ @include_once('local.settings.php'); }"
  with_items: settings.stdout_lines
  become: yes
  become_method: sudo
  tags:
    - all-sites
    - single-site

- name: Copy upgrade script
  copy: src=neticrm_update.sh dest=/usr/local/bin/neticrm_update.sh mode=0755 owner=answerable
  become: yes
  become_method: sudo
  tags:
    - upgrade-db
    - load
    - deploy-7
    - deploy-6
    - upgrade-7
    - upgrade-6

- name: Copy cache clear script
  copy: src=drupal_cache_clear.sh dest=/usr/local/bin/drupal_cache_clear.sh mode=0755 owner=answerable
  become: yes
  become_method: sudo
  tags:
    - cache-clear-all
    - cache-clear-css-js
    - cache-clear-site
    - load
    - deploy-7
    - deploy-6
    - upgrade-7
    - upgrade-6

# cache clear
- name: Clear cache and NOT run upgrade database script
  shell: bash -c "/usr/local/bin/neticrm_update.sh"
  become: yes
  become_method: sudo
  tags:
    - cache-clear-site

# cache clear and updb
- name: Clear cache and run upgrade database script
  shell: bash -c "/usr/local/bin/neticrm_update.sh --updb"
  become: yes
  become_method: sudo
  tags: upgrade-db

- name: Copy enable crm module to place
  copy: src=enable_crm_module.sh dest=/usr/local/bin/enable_crm_module.sh mode=0755 owner=answerable
  become: yes
  become_method: sudo
  tags:
    - load

# cache clear
- name: Run drush cache-clear all
  shell: bash -c "/usr/local/bin/drupal_cache_clear.sh all"
  become: yes
  become_method: sudo
  tags:
    - cache-clear-all

- name: Run drush cache-clear css-js
  shell: bash -c "/usr/local/bin/drupal_cache_clear.sh css-js"
  become: yes
  become_method: sudo
  tags:
    - cache-clear-css-js
